name: atividade_flutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  path: ^1.9.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ifpi_logo.png
    - assets/map_style.txt
